### ISSUE TITLE
Add multiple config files support

### ISSUE THREAD

**Issue by lzhoucs** [Availity/availity-ekko#32]
Currently routes are configured through `routes.json` file.  It is good only for smaller size of apps. In a larger app where different teams develop different APIs, it becomes a pain to maintain this file. Merge conflicts occur very often. And this file gets easily corrupted by a bad merge - it has happened quite some times in our dev env, and when this happens, the app stopped working locally.

@bobbennett can correct me if I am wrong.

If routes can be configured in a dir instead of a single file, we can split up this file into multiple json configs where each team updates their own portion, things would become more manageable.

**Comment by robmcguinness** [comment]
i think the ultimate goal is to figure out a way to share versioned configurations through something like npm.  thoughts?

**Comment by joshbowman** [comment]
I don't know how much sharing of mocked data there would be across apps that we would want to package it separately from the source.  Even for commonly used endpoints, the specific data that you want to mock is often different per template.

I agree that something should probably be done to make the mocked data more maintainable though.  Routes.json is getting to be several hundred lines long in several of our apps.  The merge conflicts are very easy to get wrong.

**Comment by lzhoucs** [comment]
Do we have company private npm registry up and running, or are we using npm enterprise? 

I agree we might want to maintain _some_ configurations separately as a standalone npm module, but they are meaningless to the public domain. 

Also not all the configurations are eligible to be maintained that way. Some configs, like those routes, are so app specific that we might want to have those built in to the app.

**Comment by robmcguinness** [comment]
Sorry this has been left open for soo long.  I think we can solve this multiple ways:
- expand the configuration loader to support multiple entry points for configuration files (directories)

``` js
{
 development: {
  routes: [
   path.join(__dirname, '/routes1.json'),
   path.join(__dirname, '../some/other/path/routes2.json')
  ]
 }
}
```
- allow for npm modules to extend the routes configuration with their own mock data like:

``` bash
npm install availity-api-v1-data
```

As long as we log detectable route conflicts i think this will work.

**Comment by robmcguinness** [comment]
@joshbowman and @lzhoucs  let me know if this alleviates your issue.  if not we can reopen.

**Comment by lzhoucs** [comment]
I think the solutions solves our problem nicely. All we need to do is to upgrade our dependency. Right now we are still using 0.2.x. Hopefully there's not a lot API change for the mock data, otherwise it is gonna be a painful process to update the mock data line by line manually. Some of them are over 2K lines! :)

**Comment by robmcguinness** [comment]
@lzhoucs after scanning the release log https://github.com/Availity/availity-ekko/releases I don't believe there are any breaking changes
