### ISSUE TITLE
Middleware configuration doesn't support custom environments

### ISSUE THREAD

**Issue by bobbennett** [Availity/availity-ekko#37]
In [middleware/index.js:L9-11](https://github.com/Availity/availity-ekko/blob/master/server/middleware/index.js#L9-L11), the code is pulling in 3 environments (development, testing, and production); however, in [server/index.js:L27-28](https://github.com/Availity/availity-ekko/blob/master/server/index.js#L27-L28), we pull the environment from the `NODE_ENV` variable. This variable can be set to anything the developer wants, but setting it to anything other than the 3 environments listed will result in an error:

`TypeError: middleware[(environment || "development")] is not a function`

The most flexible option would probably be to allow the developer to add their own middleware function for their environment.

Also, I don't believe the [availity-toolkit scripts](https://github.com/Availity/availity-toolkit/blob/master/package.json#L34-L35) will run for staging and integration since there is no staging or integration middleware setup. I haven't tried though.

**Comment by robmcguinness** [comment]
Ekko was built from an internal application that actually used the different middleware options.   I was actually thinking about removing them in v2.0 since most use Ekko for it's mock and proxy features.

What would be the use case for `production` version of Ekko?

**Comment by bobbennett** [comment]
We're only using the development environment. I went to add a demo environment to the config and it blew up bc I didn't use one of those 3 environment strings.

I wasn't modifying the middleware, just couldn't use the config the way I was trying

**Comment by robmcguinness** [comment]
ok if there is a use case then we can retro.  if not, we should probably clean up the code base and remove a bunch of stuff that isn't used for mock and proxy.

**Comment by bobbennett** [comment]
I'm good with that. Probably could do away with environment specific middleware and just have a single middleware setup

**Comment by robmcguinness** [comment]
environment configurations were removed in `v2`.
