### ISSUE TITLE
Proxy contexts don't trigger

### ISSUE THREAD

**Issue by ivern** [Availity/availity-ekko#7]
Using the following configuration:

```
servers: {
  web: {
    host: '0.0.0.0',
    port: 8090
  },
  aries: {
    port: 8280,
    proxy: true,
    proxies: [
      {
        context: "/api",
        rewrite: {
          from: "^/api",
          to: ""
        }
      },
      {
        context: "/public/api",
        rewrite: {
          from: "^/public/api",
          to: ""
        }
      }
    ]
  },
  axi: {
    port: 8080,
    proxy: true,
    proxies: [
      {
        context: "/availity"
      }
    ]
  }
}
```

  }

I can't get the proxy routes to fire.  What appears to be happening is that by the time proxy.js gets the request URL to process, req.url already has the context stripped.  It's getting /v1/blah instead of /api/v1/blah, which means the matcher never fires.

**Comment by robmcguinness** [comment]
should be closed with https://github.com/Availity/availity-ekko/releases/tag/v0.2.0

**Comment by robmcguinness** [comment]
@ivern have you tried the latest version?

**Comment by KaseyPowers** [comment]
I believe this has been fixed, if it is still occurring please reopen.
